# TCL File Generated by Component Editor 16.1
# Mon Mar 06 19:39:49 CET 2017
# DO NOT MODIFY


# 
# pio_n "pio_n" v1.0
#  2017.03.06.19:39:49
# 
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1


# 
# module pio_n
# 
set_module_property DESCRIPTION ""
set_module_property NAME pio_n
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property GROUP "Processors and Peripherals/Peripherals"
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME pio_n
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL pio_n
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE true
add_fileset_file pio_n.vhd VHDL PATH pio_n.vhd TOP_LEVEL_FILE


# 
# parameters
# 
add_parameter RegCnt POSITIVE 256 ""
set_parameter_property RegCnt DEFAULT_VALUE 256
set_parameter_property RegCnt DISPLAY_NAME RegCnt
set_parameter_property RegCnt WIDTH ""
set_parameter_property RegCnt TYPE POSITIVE
set_parameter_property RegCnt UNITS None
set_parameter_property RegCnt ALLOWED_RANGES 1:2147483647
set_parameter_property RegCnt DESCRIPTION ""
set_parameter_property RegCnt HDL_PARAMETER true
add_parameter ByteEnable BOOLEAN false ""
set_parameter_property ByteEnable DEFAULT_VALUE false
set_parameter_property ByteEnable DISPLAY_NAME ByteEnable
set_parameter_property ByteEnable WIDTH ""
set_parameter_property ByteEnable TYPE BOOLEAN
set_parameter_property ByteEnable UNITS None
set_parameter_property ByteEnable DESCRIPTION ""
set_parameter_property ByteEnable HDL_PARAMETER true


# 
# display items
# 


# 
# connection point clk
# 
add_interface clk clock end
set_interface_property clk clockRate 0
set_interface_property clk ENABLED true
set_interface_property clk EXPORT_OF ""
set_interface_property clk PORT_NAME_MAP ""
set_interface_property clk CMSIS_SVD_VARIABLES ""
set_interface_property clk SVD_ADDRESS_GROUP ""

add_interface_port clk clk clk Input 1


# 
# connection point reset
# 
add_interface reset reset end
set_interface_property reset associatedClock clk
set_interface_property reset synchronousEdges DEASSERT
set_interface_property reset ENABLED true
set_interface_property reset EXPORT_OF ""
set_interface_property reset PORT_NAME_MAP ""
set_interface_property reset CMSIS_SVD_VARIABLES ""
set_interface_property reset SVD_ADDRESS_GROUP ""

add_interface_port reset reset reset Input 1


# 
# connection point data
# 
add_interface data conduit end
set_interface_property data associatedClock clk
set_interface_property data associatedReset reset
set_interface_property data ENABLED true
set_interface_property data EXPORT_OF ""
set_interface_property data PORT_NAME_MAP ""
set_interface_property data CMSIS_SVD_VARIABLES ""
set_interface_property data SVD_ADDRESS_GROUP ""

add_interface_port data data_in_value data_in_value Input regcnt*32
add_interface_port data data_in_read data_in_read Output regcnt
add_interface_port data data_out_value data_out_value Output regcnt*32
add_interface_port data data_out_write data_out_write Output regcnt


# 
# connection point avl_mm
# 
add_interface avl_mm avalon end
set_interface_property avl_mm addressUnits WORDS
set_interface_property avl_mm associatedClock clk
set_interface_property avl_mm associatedReset reset
set_interface_property avl_mm bitsPerSymbol 8
set_interface_property avl_mm burstOnBurstBoundariesOnly false
set_interface_property avl_mm burstcountUnits WORDS
set_interface_property avl_mm explicitAddressSpan 0
set_interface_property avl_mm holdTime 0
set_interface_property avl_mm linewrapBursts false
set_interface_property avl_mm maximumPendingReadTransactions 0
set_interface_property avl_mm maximumPendingWriteTransactions 0
set_interface_property avl_mm readLatency 0
set_interface_property avl_mm readWaitTime 1
set_interface_property avl_mm setupTime 0
set_interface_property avl_mm timingUnits Cycles
set_interface_property avl_mm writeWaitTime 0
set_interface_property avl_mm ENABLED true
set_interface_property avl_mm EXPORT_OF ""
set_interface_property avl_mm PORT_NAME_MAP ""
set_interface_property avl_mm CMSIS_SVD_VARIABLES ""
set_interface_property avl_mm SVD_ADDRESS_GROUP ""

add_interface_port avl_mm avl_mm_address address Input 8
add_interface_port avl_mm avl_mm_writedata writedata Input 32
add_interface_port avl_mm avl_mm_chipselect chipselect Input 1
add_interface_port avl_mm avl_mm_readdata readdata Output 32
add_interface_port avl_mm avl_mm_read read Input 1
add_interface_port avl_mm avl_mm_writebyteenable writebyteenable Input 4
set_interface_assignment avl_mm embeddedsw.configuration.isFlash 0
set_interface_assignment avl_mm embeddedsw.configuration.isMemoryDevice 0
set_interface_assignment avl_mm embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment avl_mm embeddedsw.configuration.isPrintableDevice 0


# +-----------------------------------
# | Device tree generation
# |
set_module_assignment embeddedsw.dts.vendor "westteam"
set_module_assignment embeddedsw.dts.compatible " snps,pio_n"
set_module_assignment embeddedsw.dts.group "pio"
# |
# +-----------------------------------
